/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import ADT.LList;
import ADT.ListInterface;
import Entity.CatalogProduct;
import Entity.Promotion;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author User
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form CreatePromotion
     */ 
    public Product() {
        initComponents();
        initialize();
    }
    public void CloseFrame(){
    super.dispose();
    }   
    ListInterface<Promotion> promotionList = new LList<>();
    ListInterface<CatalogProduct> productList = new LList<>();  
    File srcFolder;
    File destFolder;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton10 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        create = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        fDescription = new javax.swing.JTextArea();
        Price = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        Image = new javax.swing.JLabel();
        path = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        uName = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        uDescription = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        uPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MaintainBrowse1 = new javax.swing.JButton();
        uType = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        uImage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uStatus = new javax.swing.JTextField();
        ChooseStatus = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProductDetails = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBox1.setText("jCheckBox1");

        jButton10.setText("jButton10");

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flower Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setAutoscrolls(true);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        Reset.setText("Cancel");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel22.setText("Photo");

        jLabel23.setText("Flower Name");

        jLabel24.setText("Price");

        jLabel25.setText("Description");

        fDescription.setColumns(20);
        fDescription.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        fDescription.setRows(5);
        jScrollPane4.setViewportView(fDescription);

        Price.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        fName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        jLabel26.setText("Quantity");

        Quantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel27.setText("Type");

        jDesktopPane4.setBackground(new java.awt.Color(255, 255, 255));

        Image.setBackground(new java.awt.Color(0, 0, 0));
        Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane4.setLayer(Image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        path.setText("path");

        Type.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(277, 277, 277)
                                        .addComponent(create)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Reset))
                                    .addComponent(jScrollPane4)
                                    .addComponent(Price)
                                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fName, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                                    .addComponent(Type))))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(browse)
                            .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(path)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(Reset))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel7);

        jTabbedPane2.addTab("Create Flower", jScrollPane2);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        reset.setText("Cancel");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel28.setText("Flower Name");

        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });

        uDescription.setColumns(20);
        uDescription.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        uDescription.setRows(5);
        jScrollPane5.setViewportView(uDescription);

        jLabel29.setText("Description");

        jLabel30.setText("Price");

        uPrice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel8.setText("Photo");

        MaintainBrowse1.setText("Browse");
        MaintainBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintainBrowse1ActionPerformed(evt);
            }
        });

        uType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel32.setText("Type");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jDesktopPane5.setBackground(new java.awt.Color(255, 255, 255));

        uImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jDesktopPane5.setLayer(uImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uImage, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(uImage, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setText("Quantity");

        uQuantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel3.setText("Status");

        uStatus.setEditable(false);
        uStatus.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        ChooseStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Remaining Stock Rarely", "Out-of-Stock" }));
        ChooseStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel32)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MaintainBrowse1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(uStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChooseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(uPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(uType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                                .addComponent(uQuantity, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(62, 62, 62))
                    .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaintainBrowse1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ChooseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(delete)
                    .addComponent(update))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel8);

        jTabbedPane2.addTab("Maintain Flower", jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ProductDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flower ID", "Name", "Type", "Quantity", "Status", "Price(RM)", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ProductDetails);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Product Details");

        jButton1.setText("Create Promotion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Flower Details", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void initialize(){
        //add dummy flower data
        productList.add(new CatalogProduct("FL001","Lily","Bouquet","Available","Funny",120.00,120));
        productList.add(new CatalogProduct("FL002","Rose","Floral arrangement","Remaining Stock Rarely","Funny",120.00,30));
        productList.add(new CatalogProduct("FL003","Carnation","Bouquet","Out-of-Stock","Funny",120.00,0));
        productList.add(new CatalogProduct("FL004","Tuplis","Bouquet","Available","Funny",120.00,120));
           refreshFlowerDropDownList();

        DefaultTableModel model = (DefaultTableModel) ProductDetails.getModel();
          for(int i=0;i< productList.getNumberOfEntries(); i++){
              model.addRow(new Object[]{
              productList.getEntry(i+1).getProdID(),
              productList.getEntry(i+1).getProdName(),
              productList.getEntry(i+1).getProdType(),
              productList.getEntry(i+1).getProdQuantity(),
              productList.getEntry(i+1).getProdStatus(),
              productList.getEntry(i+1).getProdPrice(),
              productList.getEntry(i+1).getProdDescription(),  
              });
          }      
    }    
    public void refreshFlowerDropDownList(){
        uName.removeAllItems(); // make sure nothing in ddl
              uName.addItem(" ");
           for(int i =0 ; i<productList.getNumberOfEntries();i++){
               uName.addItem(productList.getEntry(i+1).getProdName());
           }
    }
    
    public void refreshProductTable(){
        DefaultTableModel model =(DefaultTableModel) ProductDetails.getModel();
        int rowCount = model.getRowCount();
        for(int i=rowCount-1 ; i>=0;i--){
            model.removeRow(i);
        }
   
        for(int a=0; a<productList.getNumberOfEntries(); a++){
            model.addRow(new Object[]{
              productList.getEntry(a+1).getProdID(),
              productList.getEntry(a+1).getProdName(),
              productList.getEntry(a+1).getProdType(),
              productList.getEntry(a+1).getProdQuantity(),
              productList.getEntry(a+1).getProdStatus(),
              productList.getEntry(a+1).getProdPrice(),
              productList.getEntry(a+1).getProdDescription(), 
            });
        }
    }
    
    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        Image.setIcon(new ImageIcon(f.toString()));
        filename = f.getAbsolutePath();
        path.setVisible(true);
        path.setText(filename);
    }//GEN-LAST:event_browseActionPerformed

    public String GenerateNextFLID(){
        String newID ="";
            int lastFlowerIndex = productList.getNumberOfEntries();
            String lastFlowerID = productList.getEntry(lastFlowerIndex).getProdID();
            String prefix = lastFlowerID.substring(0,2);
            int integer = Integer.parseInt(lastFlowerID.substring(2,5));
            integer +=1;
            
            newID =prefix+ String.format("%03d", integer);
            System.out.println(newID);
            System.out.println(lastFlowerIndex);
        return newID;
    }
    
    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        if(fName.getText().matches("") || Quantity.getText().matches("") || Price.getText().matches("")|| fDescription.getText().matches("") || Type.getText().matches("")){
            JOptionPane.showMessageDialog(null,"Please do not leave blank","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!Quantity.getText().matches("^[0-9]*$")){
            JOptionPane.showMessageDialog(null,"Must be numeric","Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!Price.getText().matches("^[0-9]+(\\.[0-9]{2}?)$")){
            JOptionPane.showMessageDialog(null,"Example format be like this 00.00 " ,"Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        int z = JOptionPane.showConfirmDialog(null, "Do you want to create", "Confirmation", JOptionPane.YES_OPTION);
        if(z == 0){
        //String image = path.getText();
        JOptionPane.showMessageDialog(null, "Create Successful","Information",JOptionPane.INFORMATION_MESSAGE);
        String name = fName.getText();
        String type = Type.getText();
        int quantity = Integer.parseInt(Quantity.getText());
        double price = Double.parseDouble(Price.getText());
        String description = fDescription.getText();
        CatalogProduct flower = new CatalogProduct(GenerateNextFLID(),name,type,description,price,quantity);
        productList.add(flower);
        
        System.out.println(productList);
            fName.setText("");
            Type.setText("");
            Quantity.setText("");
            Price.setText("");
            fDescription.setText("");
            refreshFlowerDropDownList();
            productList.add(new CatalogProduct());
            refreshProductTable();
        //srcFolder = new File(filename);
        //destFolder = new File("\\Users\\User\\Desktop\\Agile-Assignment\\src\\UI\\Image" );

        /*if(!srcFolder.exists()){
            System.out.println("Directory does not exist.");
        }
        else
        {
            try{
                copyFolder(srcFolder,destFolder);
            }catch(IOException e){
                e.printStackTrace();
            }}*/
        }
        else if(z == 1){
            JOptionPane.showMessageDialog(null, "Create cancel","Information", JOptionPane.INFORMATION_MESSAGE);
            fName.setText("");
            Type.setText("");
            Quantity.setText("");
            Price.setText("");
            fDescription.setText("");
        }

        }
    }//GEN-LAST:event_createActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(uType.getText().matches("") || uQuantity.getText().matches("") || uPrice.getText().matches("") || uDescription.getText().matches("")){
            JOptionPane.showMessageDialog(null,"Please do not leave blank","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!uQuantity.getText().matches("^[0-9]*$")){
            JOptionPane.showMessageDialog(null,"must in numeric","Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!uPrice.getText().matches("^[0-9]+(\\.[0-9]{2}?)$")){
            JOptionPane.showMessageDialog(null,"Example format be like this 00.00","Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        int s = JOptionPane.showConfirmDialog(null, "Do you want to update","Confirmation", JOptionPane.YES_NO_OPTION);
        if(s==0){
            // update the specific flower information
            for( int i=0;i<productList.getNumberOfEntries();i++){
            if(uName.getSelectedItem() == productList.getEntry(i+1).getProdName()){
                JOptionPane.showMessageDialog(null, "Product record :"+productList.getEntry(i+1).getProdName()+" has been successfully updated.","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                productList.getEntry(i+1).setProdStatus(uStatus.getText());
                productList.getEntry(i+1).setProdType(uType.getText());
                productList.getEntry(i+1).setProdPrice(Double.parseDouble(uPrice.getText()));
                productList.getEntry(i+1).setProdQuantity(Integer.parseInt(uQuantity.getText()));
                productList.getEntry(i+1).setProdDescription(uDescription.getText());
                
            }
        }
        JOptionPane.showMessageDialog(null, "Updated successful","Information", JOptionPane.INFORMATION_MESSAGE);
        ImageIcon imgThisImg = new ImageIcon("\\Users\\User\\Desktop\\Agile-Assignment\\src\\UI\\Image\\white.png");
        uImage.setIcon(imgThisImg);
        uStatus.setText("");
        uName.setSelectedItem("");
        uType.setText("");
        uQuantity.setText("");
        uPrice.setText("");
        uDescription.setText("");
        refreshFlowerDropDownList();
        refreshProductTable();
        }
        else if(s==1){
        JOptionPane.showMessageDialog(null,"Update cancel","Information",JOptionPane.INFORMATION_MESSAGE);}
        ImageIcon imgThisImg = new ImageIcon("\\Users\\User\\Desktop\\Agile-Assignment\\src\\UI\\Image\\white.png");
        uImage.setIcon(imgThisImg);
        uStatus.setText("");
        uName.setSelectedItem("");
        uType.setText("");
        uQuantity.setText("");
        uPrice.setText("");
        uDescription.setText("");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void MaintainBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintainBrowse1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        uImage.setIcon(new ImageIcon(f.toString()));
        filename = f.getAbsolutePath();
    }//GEN-LAST:event_MaintainBrowse1ActionPerformed
    
    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        for( int i=0;i<productList.getNumberOfEntries();i++){
            if(uName.getSelectedItem() == productList.getEntry(i+1).getProdName()){
                
            ImageIcon imgThisImg = new ImageIcon("\\Users\\User\\Desktop\\Agile-Assignment\\src\\UI\\Image\\Rose.jpeg");
            uImage.setIcon(imgThisImg);
            uStatus.setText(productList.getEntry(i+1).getProdStatus());
            uType.setText(productList.getEntry(i+1).getProdType());
            uQuantity.setText(productList.getEntry(i+1).getProdQuantity()+"");
            uPrice.setText(productList.getEntry(i+1).getProdPrice()+"");
            uDescription.setText(productList.getEntry(i+1).getProdDescription());
            }
        }    
    }//GEN-LAST:event_uNameActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        for( int i=0;i<productList.getNumberOfEntries();i++){
            if(uName.getSelectedItem() == productList.getEntry(i+1).getProdName()){
                JOptionPane.showMessageDialog(null, "Product record :"+productList.getEntry(i+1).getProdName()+" has been successfully deleted.","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                productList.remove(i+1);
                uStatus.setText("");
                uType.setText("");
                uQuantity.setText("");
                uPrice.setText("");
                uDescription.setText("");
                System.out.print(productList);
            }
        }
        refreshFlowerDropDownList();
    }//GEN-LAST:event_deleteActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        ImageIcon imgThisImg = new ImageIcon("\\Users\\User\\Desktop\\Agile-Assignment\\src\\UI\\Image\\white.png");
        uStatus.setText("");
        uImage.setIcon(imgThisImg);
        uName.setSelectedItem("");
        uType.setText("");
        uQuantity.setText("");
        uPrice.setText("");
        uDescription.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        fName.setText("");
        Type.setText("");
        Quantity.setText("");
        Price.setText("");
        fDescription.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void ChooseStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseStatusActionPerformed
        if(ChooseStatus.getSelectedItem() == "Available"){
            uStatus.setText("Available");
        }
        else if(ChooseStatus.getSelectedItem() == "Remaining Stock Rarely"){
            uStatus.setText("Remaining Stock Rarely");
        }
        else if(ChooseStatus.getSelectedItem() == "Out-of-Stock"){
            uStatus.setText("Out-Of-Stock");
        }
    }//GEN-LAST:event_ChooseStatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new PromotionDetail().setVisible(true);
        CloseFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    /*public static void copyFolder(File src, File dest)throws IOException{  	
    	if(src.isDirectory()){
    		
    		//if directory not exists, create it
    		if(!dest.exists()){
    		   dest.mkdir();
    		   System.out.println("Directory copied from " + src + "  to " + dest);
    		}
    		
    		//list all the directory contents
    		String files[] = src.list();
    		
    		for (String file : files) {
    		   //construct the src and dest file structure
    		   File srcFile = new File(src, file);
    		   File destFile = new File(dest, file);
    		   //recursive copy
    		   copyFolder(srcFile,destFile);
    		}
    	   
    	}else{
    		//if file, then copy it
    		//Use bytes stream to support all file types
    		InputStream in = new FileInputStream(src);
    	        OutputStream out = new FileOutputStream(dest); 
    	                     
    	        byte[] buffer = new byte[1024];
    	    
    	        int length;
    	        //copy the file content in bytes 
    	        while ((length = in.read(buffer)) > 0){
    	    	   out.write(buffer, 0, length);
    	        }
 
    	        in.close();
    	        out.close();
    	        System.out.println("File copied from " + src + " to " + dest);
    	}
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */ 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new Product().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ChooseStatus;
    private javax.swing.JLabel Image;
    private javax.swing.JButton MaintainBrowse1;
    private javax.swing.JTextField Price;
    private javax.swing.JTable ProductDetails;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Type;
    private javax.swing.JButton browse;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea fDescription;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel path;
    private javax.swing.JButton reset;
    private javax.swing.JTextArea uDescription;
    private javax.swing.JLabel uImage;
    private javax.swing.JComboBox<String> uName;
    private javax.swing.JTextField uPrice;
    private javax.swing.JTextField uQuantity;
    private javax.swing.JTextField uStatus;
    private javax.swing.JTextField uType;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
byte[] photo = null;
String filename = null;
}
